### ISSUE TITLE
TEST9 macro definition missing from tmpl_complex_time_tests.h

### ISSUE THREAD

**Issue by tcumby** [ryanmaguire/libtmpl#10]
Hi Ryan,

Hopefully me reporting this is useful. 

This macro is referenced in `tests/complex_tests/time_tests/tmpl_complex_expi*.c` and `tests/complex_test/time_tests/tmpl_complex_expipi*.c`

Best regards,
Ty

**Comment by ryanmaguire** [comment]
Hm, curious.
It's there on the specfuncoptics branch.

Was it missing from your pull request with those complex tests?
I might have missed that when merging.

I've copied it from the specfuncoptics branch back to the master, so should be fixed now.
